spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaming_project?autoReconnect=true&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

logging:
  level:
    ROOT: INFO
    web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

server:
  port: 8280


